sgd
===========

```{r knitr_options, echo=FALSE}

opts_chunk$set(warning = FALSE)

```

```{r setup, message=FALSE}

ptm <- proc.time()

library(sgd)
library(rbenchmark)

set.seed(42)

data(iris)
y <- matrix(as.numeric(iris$Species == "versicolor"))
multiclass_y <- model.matrix(~ Species - 1, data = iris)
X <- model.matrix(Species ~ Sepal.Length + Sepal.Width, data = iris)

```

##### using `stats::glm` for binary classification

```{r glm}

coef(glm(y ~ X - 1, family = binomial))

```


##### batch

```{r batch}

batch <- LogisticRegression(epochs = 1500, learning_rate = 0.1, momentum = 0.99, minibatch_size = 0)
batch$Fit(X, y)
batch$Coef()

```

##### minibatch

```{r minibatch}

minibatch <- LogisticRegression(epochs = 1e4, learning_rate = 0.01, momentum = 0.99, minibatch_size = 10)
minibatch$Fit(X, y)
minibatch$Coef()

```

##### stochastic

```{r stochastic}

stochastic <- LogisticRegression(epochs = 1e4, learning_rate = 0.01, momentum = 0.99, minibatch_size = 1)
stochastic$Fit(X, y)
stochastic$Coef()

```

## multiclass

```{r multiclass}

multiclass <- LogisticRegression(epochs = 1e4, learning_rate = 0.01, momentum = 0.99, minibatch_size = 10)
multiclass$Fit(X, multiclass_y)

preds <- multiclass$Predict(X)
preds <- t(apply(preds, 1, function(x) x / sum(x) ))

by(preds, iris$Species, colMeans)

```

# Benchmarks

```{r benchmark_setup, echo=FALSE}

sigmoid <- function(x) 1 / (1 + exp(-x))
activation <- function(X, w) sigmoid(X %*% w)
gradient <- function(X, y, h) t(X) %*% (h - y)

sgd_R <- function(X, y, epochs, learning_rate, momentum)
  {
    
    n <- nrow(X)
    p <- ncol(X)
    k <- ncol(y)

    w <- matrix(rnorm(p * k), p, k)
    delta_w <- matrix(0, p, k)

    for (e in 1:epochs) {

      h <- activation(X, w)
      g <- gradient(X, y, h)

      delta_w <- momentum * delta_w + (1 - momentum) * learning_rate * g
      w <- w - delta_w
      
    }

    return(w)
    
  }

```

## Iris benchmarks

```{r small_bench}

data(iris)
set.seed(42)

y <- matrix(as.numeric(iris$Species == "versicolor"))
X <- model.matrix(Species ~ Sepal.Length + Sepal.Width, data = iris)
X[,-1] <- scale(X[,-1])

sgd <- LogisticRegression(epochs = 500, learning_rate = 0.01, momentum = 0.95, minibatch_size = 0)

benchmark(
    glm = glm(y ~ X - 1, family = binomial),
    sgd_R = sgd_R(X, y, 500, 0.01, 0.95),
    sgd = sgd$Fit(X, y),
    replications = 100
  )

```

## Test against MNIST data

```{r setup_mnist, echo=FALSE}

untar("mnist.csv.tar.gz")
d <- read.csv("mnist.csv")
d[-1] <- scale(d[-1]) ## quick

train_idx <- sample(1:10, nrow(d), replace = TRUE)

train <- d[train_idx != 1,]

nan <- sapply(train, function(x) any(is.nan(x)) )

train <- train[!nan]
valid <- d[train_idx == 1, !nan]

train_X <- model.matrix(label ~ ., data = train)
train_y <- model.matrix(~ factor(train$label) - 1)

valid_X <- model.matrix(label ~ ., data = valid)
```

```{r test_mnist}

mnist <- LogisticRegression(momentum = 0.95, minibatch_size = 0)
mnist$Fit(train_X, train_y)

valid_pred <- mnist$Predict_class(valid_X) - 1

```

missclassification rate: `r mean(valid_pred != valid$label)`


## More benchmarks to come

```{r moar_benchmarks, eval=FALSE, echo=FALSE}

benchmark(
    glm = glm(train_y[1:5000,1] ~ train_X[1:5000,], family = binomial),
    sgd_batch = stochastic_gradient_descent(train_X[1:5000,], train_y[1:5000, 1, drop = FALSE], 100, 0.01, 0.99, nrow(train_X), shuffle = FALSE),
    sgd_mb100 = stochastic_gradient_descent(train_X[1:5000,], train_y[1:5000, 1, drop = FALSE], 100, 0.01, 0.99, 100),
    sgd_stochastic = stochastic_gradient_descent(train_X[1:5000,], train_y[1:5000, 1, drop = FALSE], 100, 0.01, 0.99, 1),
  replications = 1
  )

```

```{r wrapup}

proc.time() - ptm
sessionInfo()

```

```{r cleanup, echo=FALSE}

invisible(file.remove("mnist.csv"))

```
