# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shuffle_matrix <- function(A) {
    .Call('sgd_shuffle_matrix', PACKAGE = 'sgd', A)
}

sigmoid <- function(x) {
    .Call('sgd_sigmoid', PACKAGE = 'sgd', x)
}

stochastic_gradient_descent <- function(X, y, max_epoch, learning_rate, momentum, minibatch_size = 100L, shuffle = TRUE, verbose = FALSE, tol = 1.0e-7) {
    .Call('sgd_stochastic_gradient_descent', PACKAGE = 'sgd', X, y, max_epoch, learning_rate, momentum, minibatch_size, shuffle, verbose, tol)
}

