# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stochastic_gradient_descent <- function(X, y, max_epoch, learning_rate, momentum, minibatch_size = 100L, shuffle = TRUE, verbosity = 0L, tol = 1.0e-7) {
    .Call('sgd_stochastic_gradient_descent', PACKAGE = 'sgd', X, y, max_epoch, learning_rate, momentum, minibatch_size, shuffle, verbosity, tol)
}

