# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient_descent <- function(X, y, max_epoch, learning_rate, momentum, tol) {
    .Call('sgd_gradient_descent', PACKAGE = 'sgd', X, y, max_epoch, learning_rate, momentum, tol)
}

sigmoid <- function(x) {
    .Call('sgd_sigmoid', PACKAGE = 'sgd', x)
}

stochastic_gradient_descent <- function(X, y, max_epoch, learning_rate, momentum, tol) {
    .Call('sgd_stochastic_gradient_descent', PACKAGE = 'sgd', X, y, max_epoch, learning_rate, momentum, tol)
}

